
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action QuitButton;

	private global::Gtk.Action OpenInputButton;

	private global::Gtk.Action SaveInputButton;

	private global::Gtk.Action OpenPhaseButton;

	private global::Gtk.Action SavePhaseButton;

	private global::Gtk.Action ComputePhaseButton;

	private global::Gtk.ToggleAction AddPointsButton;

	private global::Gtk.Action RemovePointButton;

	private global::Gtk.Action DeletePointsButton;

	private global::Gtk.Action ComputeMultipointsPhase;

	private global::Gtk.Action ComputePropagationButton;

	private global::Gtk.Action SaveReconstructionButton;

	private global::Gtk.Fixed MainLayout;

	private global::Gtk.Toolbar MainToolbar;

	private global::Gtk.Notebook MainNotebook;

	private global::Gtk.Fixed PageInputLayout;

	private global::Gtk.VScrollbar InputScrollY;

	private global::Gtk.EventBox InputEventBox;

	private global::Gtk.Image InputImage;

	private global::Gtk.HScrollbar InputScrollX;

	private global::Gtk.Toolbar InputToolbar;

	private global::Gtk.Notebook TargetNotebook;

	private global::Gtk.Fixed LayoutPagePoints;

	private global::Gtk.ScrolledWindow PointsWindow;

	private global::Gtk.TextView PointsView;

	private global::Gtk.Toolbar PointsToolbar;

	private global::Gtk.SpinButton NFFT;

	private global::Gtk.Label LabelNFFT;

	private global::Gtk.Entry Elapsed;

	private global::Gtk.Label LabelElapsed;

	private global::Gtk.Label LabelPagePoints;

	private global::Gtk.Label LabelPageInput;

	private global::Gtk.Fixed LayoutPagePhase;

	private global::Gtk.VScrollbar PhaseScrollY;

	private global::Gtk.Image PhaseImage;

	private global::Gtk.HScrollbar PhaseScrollX;

	private global::Gtk.SpinButton Iterations;

	private global::Gtk.Label LabelIterations;

	private global::Gtk.Toolbar PhaseToolbar;

	private global::Gtk.CheckButton LensPhase;

	private global::Gtk.SpinButton LensZ;

	private global::Gtk.HScrollbar LensZScroll;

	private global::Gtk.Label LabelLensZ;

	private global::Gtk.SpinButton Pitch;

	private global::Gtk.SpinButton Wavelength;

	private global::Gtk.Label LabelWavelength;

	private global::Gtk.Label LabelPitch;

	private global::Gtk.CheckButton BlazedPhase;

	private global::Gtk.SpinButton BlazedX;

	private global::Gtk.HScrollbar BlazedScrollX;

	private global::Gtk.Label LabelBlazedX;

	private global::Gtk.SpinButton BlazedY;

	private global::Gtk.HScrollbar BlazedScrollY;

	private global::Gtk.Label LabelBlazedY;

	private global::Gtk.CheckButton GerchbergSaxtonPhase;

	private global::Gtk.Entry PhaseElapsed;

	private global::Gtk.Label LabelPhaseElapsed;

	private global::Gtk.Label LabelPagePhase;

	private global::Gtk.Fixed LayoutPageReconstruction;

	private global::Gtk.Image ReconImage;

	private global::Gtk.VScrollbar ReconScrollY;

	private global::Gtk.HScrollbar ReconScrollX;

	private global::Gtk.Label LabelPropagation;

	private global::Gtk.SpinButton PropagationZ;

	private global::Gtk.HScrollbar PropagationScrollZ;

	private global::Gtk.Label LabelPropagationZ1;

	private global::Gtk.Toolbar ReconToolbar;

	private global::Gtk.SpinButton PropagationWavelength;

	private global::Gtk.Label LabelPropagationWavelength;

	private global::Gtk.SpinButton PropagationPitch;

	private global::Gtk.Label LabelPropagationPitch;

	private global::Gtk.Entry ReconElapsed;

	private global::Gtk.Label LabelReconElapsed;

	private global::Gtk.Label LabelPageReconstruction;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.QuitButton = new global::Gtk.Action("QuitButton", null, global::Mono.Unix.Catalog.GetString("Exit Phase Explorer"), "gtk-quit");
		w1.Add(this.QuitButton, null);
		this.OpenInputButton = new global::Gtk.Action("OpenInputButton", null, global::Mono.Unix.Catalog.GetString("Open target pattern"), "gtk-open");
		w1.Add(this.OpenInputButton, null);
		this.SaveInputButton = new global::Gtk.Action("SaveInputButton", null, global::Mono.Unix.Catalog.GetString("Save target pattern"), "gtk-save");
		w1.Add(this.SaveInputButton, null);
		this.OpenPhaseButton = new global::Gtk.Action("OpenPhaseButton", null, global::Mono.Unix.Catalog.GetString("Open phase pattern"), "gtk-open");
		w1.Add(this.OpenPhaseButton, null);
		this.SavePhaseButton = new global::Gtk.Action("SavePhaseButton", null, global::Mono.Unix.Catalog.GetString("Save phase pattern"), "gtk-save");
		w1.Add(this.SavePhaseButton, null);
		this.ComputePhaseButton = new global::Gtk.Action("ComputePhaseButton", null, global::Mono.Unix.Catalog.GetString("Compute phase pattern"), "gtk-media-play");
		w1.Add(this.ComputePhaseButton, null);
		this.AddPointsButton = new global::Gtk.ToggleAction("AddPointsButton", null, global::Mono.Unix.Catalog.GetString("Enable edit mode"), "gtk-edit");
		w1.Add(this.AddPointsButton, null);
		this.RemovePointButton = new global::Gtk.Action("RemovePointButton", null, global::Mono.Unix.Catalog.GetString("Remove points"), "gtk-remove");
		w1.Add(this.RemovePointButton, null);
		this.DeletePointsButton = new global::Gtk.Action("DeletePointsButton", null, global::Mono.Unix.Catalog.GetString("Remove all points"), "gtk-delete");
		w1.Add(this.DeletePointsButton, null);
		this.ComputeMultipointsPhase = new global::Gtk.Action("ComputeMultipointsPhase", null, global::Mono.Unix.Catalog.GetString("Compute phase pattern"), "gtk-media-play");
		w1.Add(this.ComputeMultipointsPhase, null);
		this.ComputePropagationButton = new global::Gtk.Action("ComputePropagationButton", null, global::Mono.Unix.Catalog.GetString("Compute propagation"), "gtk-media-play");
		w1.Add(this.ComputePropagationButton, null);
		this.SaveReconstructionButton = new global::Gtk.Action("SaveReconstructionButton", null, global::Mono.Unix.Catalog.GetString("Save reconstruction"), "gtk-save");
		w1.Add(this.SaveReconstructionButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 800;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("PhaseExplorer.hologram.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainLayout = new global::Gtk.Fixed();
		this.MainLayout.Name = "MainLayout";
		this.MainLayout.HasWindow = false;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'MainToolbar\'><toolitem name=\'QuitButton\' action=\'QuitButton\'/>" +
				"</toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MainToolbar")));
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.MainToolbar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainToolbar]));
		w2.X = 20;
		w2.Y = 20;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.MainNotebook = new global::Gtk.Notebook();
		this.MainNotebook.WidthRequest = 760;
		this.MainNotebook.HeightRequest = 500;
		this.MainNotebook.Name = "MainNotebook";
		this.MainNotebook.CurrentPage = 1;
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.PageInputLayout = new global::Gtk.Fixed();
		this.PageInputLayout.Name = "PageInputLayout";
		this.PageInputLayout.HasWindow = false;
		// Container child PageInputLayout.Gtk.Fixed+FixedChild
		this.InputScrollY = new global::Gtk.VScrollbar(null);
		this.InputScrollY.HeightRequest = 256;
		this.InputScrollY.Name = "InputScrollY";
		this.InputScrollY.Adjustment.Upper = 20480D;
		this.InputScrollY.Adjustment.PageIncrement = 1D;
		this.InputScrollY.Adjustment.PageSize = 1D;
		this.InputScrollY.Adjustment.StepIncrement = 1D;
		this.PageInputLayout.Add(this.InputScrollY);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.PageInputLayout[this.InputScrollY]));
		w3.X = 20;
		w3.Y = 20;
		// Container child PageInputLayout.Gtk.Fixed+FixedChild
		this.InputEventBox = new global::Gtk.EventBox();
		this.InputEventBox.WidthRequest = 256;
		this.InputEventBox.HeightRequest = 256;
		this.InputEventBox.Name = "InputEventBox";
		// Container child InputEventBox.Gtk.Container+ContainerChild
		this.InputImage = new global::Gtk.Image();
		this.InputImage.WidthRequest = 256;
		this.InputImage.HeightRequest = 256;
		this.InputImage.Name = "InputImage";
		this.InputEventBox.Add(this.InputImage);
		this.PageInputLayout.Add(this.InputEventBox);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.PageInputLayout[this.InputEventBox]));
		w5.X = 70;
		w5.Y = 20;
		// Container child PageInputLayout.Gtk.Fixed+FixedChild
		this.InputScrollX = new global::Gtk.HScrollbar(null);
		this.InputScrollX.WidthRequest = 256;
		this.InputScrollX.Name = "InputScrollX";
		this.InputScrollX.Adjustment.Upper = 20480D;
		this.InputScrollX.Adjustment.PageIncrement = 1D;
		this.InputScrollX.Adjustment.PageSize = 1D;
		this.InputScrollX.Adjustment.StepIncrement = 1D;
		this.PageInputLayout.Add(this.InputScrollX);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.PageInputLayout[this.InputScrollX]));
		w6.X = 70;
		w6.Y = 306;
		// Container child PageInputLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'InputToolbar\'><toolitem name=\'OpenInputButton\' action=\'OpenInp" +
				"utButton\'/><toolitem name=\'SaveInputButton\' action=\'SaveInputButton\'/><toolitem " +
				"name=\'ComputeMultipointsPhase\' action=\'ComputeMultipointsPhase\'/></toolbar></ui>" +
				"");
		this.InputToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/InputToolbar")));
		this.InputToolbar.Name = "InputToolbar";
		this.InputToolbar.ShowArrow = false;
		this.InputToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.PageInputLayout.Add(this.InputToolbar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.PageInputLayout[this.InputToolbar]));
		w7.X = 70;
		w7.Y = 350;
		// Container child PageInputLayout.Gtk.Fixed+FixedChild
		this.TargetNotebook = new global::Gtk.Notebook();
		this.TargetNotebook.WidthRequest = 360;
		this.TargetNotebook.HeightRequest = 370;
		this.TargetNotebook.Name = "TargetNotebook";
		this.TargetNotebook.CurrentPage = 0;
		// Container child TargetNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPagePoints = new global::Gtk.Fixed();
		this.LayoutPagePoints.Name = "LayoutPagePoints";
		this.LayoutPagePoints.HasWindow = false;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.PointsWindow = new global::Gtk.ScrolledWindow();
		this.PointsWindow.WidthRequest = 320;
		this.PointsWindow.HeightRequest = 140;
		this.PointsWindow.Name = "PointsWindow";
		this.PointsWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child PointsWindow.Gtk.Container+ContainerChild
		this.PointsView = new global::Gtk.TextView();
		this.PointsView.Name = "PointsView";
		this.PointsView.Editable = false;
		this.PointsView.AcceptsTab = false;
		this.PointsWindow.Add(this.PointsView);
		this.LayoutPagePoints.Add(this.PointsWindow);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.PointsWindow]));
		w9.X = 20;
		w9.Y = 20;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'PointsToolbar\'><toolitem name=\'AddPointsButton\' action=\'AddPoi" +
				"ntsButton\'/><toolitem name=\'RemovePointButton\' action=\'RemovePointButton\'/><tool" +
				"item name=\'DeletePointsButton\' action=\'DeletePointsButton\'/></toolbar></ui>");
		this.PointsToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/PointsToolbar")));
		this.PointsToolbar.Name = "PointsToolbar";
		this.PointsToolbar.ShowArrow = false;
		this.PointsToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.LayoutPagePoints.Add(this.PointsToolbar);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.PointsToolbar]));
		w10.X = 20;
		w10.Y = 180;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.NFFT = new global::Gtk.SpinButton(8D, 2048D, 8D);
		this.NFFT.WidthRequest = 140;
		this.NFFT.Name = "NFFT";
		this.NFFT.Adjustment.PageIncrement = 8D;
		this.NFFT.ClimbRate = 1D;
		this.NFFT.Numeric = true;
		this.NFFT.Value = 32D;
		this.LayoutPagePoints.Add(this.NFFT);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.NFFT]));
		w11.X = 20;
		w11.Y = 230;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.LabelNFFT = new global::Gtk.Label();
		this.LabelNFFT.Name = "LabelNFFT";
		this.LabelNFFT.LabelProp = global::Mono.Unix.Catalog.GetString("FFT");
		this.LayoutPagePoints.Add(this.LabelNFFT);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.LabelNFFT]));
		w12.X = 170;
		w12.Y = 235;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.Elapsed = new global::Gtk.Entry();
		this.Elapsed.WidthRequest = 140;
		this.Elapsed.Name = "Elapsed";
		this.Elapsed.IsEditable = true;
		this.Elapsed.InvisibleChar = '•';
		this.LayoutPagePoints.Add(this.Elapsed);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.Elapsed]));
		w13.X = 20;
		w13.Y = 270;
		// Container child LayoutPagePoints.Gtk.Fixed+FixedChild
		this.LabelElapsed = new global::Gtk.Label();
		this.LabelElapsed.Name = "LabelElapsed";
		this.LabelElapsed.LabelProp = global::Mono.Unix.Catalog.GetString("Elapsed time (ms)");
		this.LayoutPagePoints.Add(this.LabelElapsed);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePoints[this.LabelElapsed]));
		w14.X = 170;
		w14.Y = 275;
		this.TargetNotebook.Add(this.LayoutPagePoints);
		// Notebook tab
		this.LabelPagePoints = new global::Gtk.Label();
		this.LabelPagePoints.Name = "LabelPagePoints";
		this.LabelPagePoints.LabelProp = global::Mono.Unix.Catalog.GetString("Points");
		this.TargetNotebook.SetTabLabel(this.LayoutPagePoints, this.LabelPagePoints);
		this.LabelPagePoints.ShowAll();
		this.PageInputLayout.Add(this.TargetNotebook);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.PageInputLayout[this.TargetNotebook]));
		w16.X = 370;
		w16.Y = 20;
		this.MainNotebook.Add(this.PageInputLayout);
		// Notebook tab
		this.LabelPageInput = new global::Gtk.Label();
		this.LabelPageInput.Name = "LabelPageInput";
		this.LabelPageInput.LabelProp = global::Mono.Unix.Catalog.GetString("Input");
		this.MainNotebook.SetTabLabel(this.PageInputLayout, this.LabelPageInput);
		this.LabelPageInput.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPagePhase = new global::Gtk.Fixed();
		this.LayoutPagePhase.Name = "LayoutPagePhase";
		this.LayoutPagePhase.HasWindow = false;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.PhaseScrollY = new global::Gtk.VScrollbar(null);
		this.PhaseScrollY.HeightRequest = 256;
		this.PhaseScrollY.Name = "PhaseScrollY";
		this.PhaseScrollY.Adjustment.Upper = 20480D;
		this.PhaseScrollY.Adjustment.PageIncrement = 1D;
		this.PhaseScrollY.Adjustment.PageSize = 1D;
		this.PhaseScrollY.Adjustment.StepIncrement = 1D;
		this.LayoutPagePhase.Add(this.PhaseScrollY);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.PhaseScrollY]));
		w18.X = 20;
		w18.Y = 20;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.PhaseImage = new global::Gtk.Image();
		this.PhaseImage.WidthRequest = 256;
		this.PhaseImage.HeightRequest = 256;
		this.PhaseImage.Name = "PhaseImage";
		this.LayoutPagePhase.Add(this.PhaseImage);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.PhaseImage]));
		w19.X = 70;
		w19.Y = 20;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.PhaseScrollX = new global::Gtk.HScrollbar(null);
		this.PhaseScrollX.WidthRequest = 256;
		this.PhaseScrollX.Name = "PhaseScrollX";
		this.PhaseScrollX.Adjustment.Upper = 20480D;
		this.PhaseScrollX.Adjustment.PageIncrement = 1D;
		this.PhaseScrollX.Adjustment.PageSize = 1D;
		this.PhaseScrollX.Adjustment.StepIncrement = 1D;
		this.LayoutPagePhase.Add(this.PhaseScrollX);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.PhaseScrollX]));
		w20.X = 70;
		w20.Y = 306;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.Iterations = new global::Gtk.SpinButton(1D, 1000D, 1D);
		this.Iterations.WidthRequest = 140;
		this.Iterations.Name = "Iterations";
		this.Iterations.Adjustment.PageIncrement = 1D;
		this.Iterations.ClimbRate = 1D;
		this.Iterations.Numeric = true;
		this.Iterations.Value = 100D;
		this.LayoutPagePhase.Add(this.Iterations);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.Iterations]));
		w21.X = 340;
		w21.Y = 50;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelIterations = new global::Gtk.Label();
		this.LabelIterations.Name = "LabelIterations";
		this.LabelIterations.LabelProp = global::Mono.Unix.Catalog.GetString("Iterations");
		this.LayoutPagePhase.Add(this.LabelIterations);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelIterations]));
		w22.X = 490;
		w22.Y = 55;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'PhaseToolbar\'><toolitem name=\'OpenPhaseButton\' action=\'OpenPha" +
				"seButton\'/><toolitem name=\'SavePhaseButton\' action=\'SavePhaseButton\'/><toolitem " +
				"name=\'ComputePhaseButton\' action=\'ComputePhaseButton\'/></toolbar></ui>");
		this.PhaseToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/PhaseToolbar")));
		this.PhaseToolbar.Name = "PhaseToolbar";
		this.PhaseToolbar.ShowArrow = false;
		this.PhaseToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.LayoutPagePhase.Add(this.PhaseToolbar);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.PhaseToolbar]));
		w23.X = 70;
		w23.Y = 350;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LensPhase = new global::Gtk.CheckButton();
		this.LensPhase.Name = "LensPhase";
		this.LensPhase.Label = global::Mono.Unix.Catalog.GetString("Add lens phase");
		this.LensPhase.DrawIndicator = true;
		this.LensPhase.UseUnderline = true;
		this.LensPhase.FocusOnClick = false;
		this.LayoutPagePhase.Add(this.LensPhase);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LensPhase]));
		w24.X = 340;
		w24.Y = 90;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LensZ = new global::Gtk.SpinButton(-10000D, 10000D, 1D);
		this.LensZ.WidthRequest = 140;
		this.LensZ.Name = "LensZ";
		this.LensZ.Adjustment.PageIncrement = 1D;
		this.LensZ.ClimbRate = 1D;
		this.LensZ.Numeric = true;
		this.LayoutPagePhase.Add(this.LensZ);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LensZ]));
		w25.X = 340;
		w25.Y = 120;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LensZScroll = new global::Gtk.HScrollbar(null);
		this.LensZScroll.WidthRequest = 400;
		this.LensZScroll.Name = "LensZScroll";
		this.LensZScroll.Adjustment.Lower = -10000D;
		this.LensZScroll.Adjustment.Upper = 10000D;
		this.LensZScroll.Adjustment.PageIncrement = 1D;
		this.LensZScroll.Adjustment.PageSize = 1D;
		this.LensZScroll.Adjustment.StepIncrement = 1D;
		this.LayoutPagePhase.Add(this.LensZScroll);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LensZScroll]));
		w26.X = 340;
		w26.Y = 160;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelLensZ = new global::Gtk.Label();
		this.LabelLensZ.Name = "LabelLensZ";
		this.LabelLensZ.LabelProp = global::Mono.Unix.Catalog.GetString("Z (&#956;m)");
		this.LabelLensZ.UseMarkup = true;
		this.LayoutPagePhase.Add(this.LabelLensZ);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelLensZ]));
		w27.X = 490;
		w27.Y = 125;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.Pitch = new global::Gtk.SpinButton(0D, 10000D, 1D);
		this.Pitch.WidthRequest = 140;
		this.Pitch.Name = "Pitch";
		this.Pitch.Adjustment.PageIncrement = 1D;
		this.Pitch.ClimbRate = 1D;
		this.Pitch.Numeric = true;
		this.LayoutPagePhase.Add(this.Pitch);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.Pitch]));
		w28.X = 340;
		w28.Y = 190;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.Wavelength = new global::Gtk.SpinButton(0D, 10000D, 1D);
		this.Wavelength.WidthRequest = 140;
		this.Wavelength.Name = "Wavelength";
		this.Wavelength.Adjustment.PageIncrement = 1D;
		this.Wavelength.ClimbRate = 1D;
		this.Wavelength.Numeric = true;
		this.LayoutPagePhase.Add(this.Wavelength);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.Wavelength]));
		w29.X = 340;
		w29.Y = 230;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelWavelength = new global::Gtk.Label();
		this.LabelWavelength.Name = "LabelWavelength";
		this.LabelWavelength.LabelProp = global::Mono.Unix.Catalog.GetString("Wavelength  (nm)");
		this.LabelWavelength.UseMarkup = true;
		this.LayoutPagePhase.Add(this.LabelWavelength);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelWavelength]));
		w30.X = 490;
		w30.Y = 235;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelPitch = new global::Gtk.Label();
		this.LabelPitch.Name = "LabelPitch";
		this.LabelPitch.LabelProp = global::Mono.Unix.Catalog.GetString("Pitch (&#956;m)");
		this.LabelPitch.UseMarkup = true;
		this.LayoutPagePhase.Add(this.LabelPitch);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelPitch]));
		w31.X = 490;
		w31.Y = 195;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.BlazedPhase = new global::Gtk.CheckButton();
		this.BlazedPhase.Name = "BlazedPhase";
		this.BlazedPhase.Label = global::Mono.Unix.Catalog.GetString("Add blazed mirror phase");
		this.BlazedPhase.DrawIndicator = true;
		this.BlazedPhase.UseUnderline = true;
		this.BlazedPhase.FocusOnClick = false;
		this.LayoutPagePhase.Add(this.BlazedPhase);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.BlazedPhase]));
		w32.X = 340;
		w32.Y = 270;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.BlazedX = new global::Gtk.SpinButton(-10000D, 10000D, 1D);
		this.BlazedX.WidthRequest = 140;
		this.BlazedX.Name = "BlazedX";
		this.BlazedX.Adjustment.PageIncrement = 1D;
		this.BlazedX.ClimbRate = 1D;
		this.BlazedX.Numeric = true;
		this.LayoutPagePhase.Add(this.BlazedX);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.BlazedX]));
		w33.X = 340;
		w33.Y = 300;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.BlazedScrollX = new global::Gtk.HScrollbar(null);
		this.BlazedScrollX.WidthRequest = 400;
		this.BlazedScrollX.Name = "BlazedScrollX";
		this.BlazedScrollX.Adjustment.Lower = -10000D;
		this.BlazedScrollX.Adjustment.Upper = 10000D;
		this.BlazedScrollX.Adjustment.PageIncrement = 1D;
		this.BlazedScrollX.Adjustment.PageSize = 1D;
		this.BlazedScrollX.Adjustment.StepIncrement = 1D;
		this.LayoutPagePhase.Add(this.BlazedScrollX);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.BlazedScrollX]));
		w34.X = 340;
		w34.Y = 340;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelBlazedX = new global::Gtk.Label();
		this.LabelBlazedX.Name = "LabelBlazedX";
		this.LabelBlazedX.LabelProp = global::Mono.Unix.Catalog.GetString("X");
		this.LayoutPagePhase.Add(this.LabelBlazedX);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelBlazedX]));
		w35.X = 490;
		w35.Y = 305;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.BlazedY = new global::Gtk.SpinButton(-10000D, 10000D, 1D);
		this.BlazedY.WidthRequest = 140;
		this.BlazedY.Name = "BlazedY";
		this.BlazedY.Adjustment.PageIncrement = 1D;
		this.BlazedY.ClimbRate = 1D;
		this.BlazedY.Numeric = true;
		this.LayoutPagePhase.Add(this.BlazedY);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.BlazedY]));
		w36.X = 340;
		w36.Y = 370;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.BlazedScrollY = new global::Gtk.HScrollbar(null);
		this.BlazedScrollY.WidthRequest = 400;
		this.BlazedScrollY.Name = "BlazedScrollY";
		this.BlazedScrollY.Adjustment.Lower = -10000D;
		this.BlazedScrollY.Adjustment.Upper = 10000D;
		this.BlazedScrollY.Adjustment.PageIncrement = 1D;
		this.BlazedScrollY.Adjustment.PageSize = 1D;
		this.BlazedScrollY.Adjustment.StepIncrement = 1D;
		this.LayoutPagePhase.Add(this.BlazedScrollY);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.BlazedScrollY]));
		w37.X = 340;
		w37.Y = 410;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelBlazedY = new global::Gtk.Label();
		this.LabelBlazedY.Name = "LabelBlazedY";
		this.LabelBlazedY.LabelProp = global::Mono.Unix.Catalog.GetString("Y");
		this.LayoutPagePhase.Add(this.LabelBlazedY);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelBlazedY]));
		w38.X = 490;
		w38.Y = 375;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.GerchbergSaxtonPhase = new global::Gtk.CheckButton();
		this.GerchbergSaxtonPhase.Name = "GerchbergSaxtonPhase";
		this.GerchbergSaxtonPhase.Label = global::Mono.Unix.Catalog.GetString("Add Gerchberg-Saxton phase");
		this.GerchbergSaxtonPhase.DrawIndicator = true;
		this.GerchbergSaxtonPhase.UseUnderline = true;
		this.GerchbergSaxtonPhase.FocusOnClick = false;
		this.LayoutPagePhase.Add(this.GerchbergSaxtonPhase);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.GerchbergSaxtonPhase]));
		w39.X = 340;
		w39.Y = 20;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.PhaseElapsed = new global::Gtk.Entry();
		this.PhaseElapsed.WidthRequest = 140;
		this.PhaseElapsed.Name = "PhaseElapsed";
		this.PhaseElapsed.IsEditable = false;
		this.PhaseElapsed.InvisibleChar = '•';
		this.LayoutPagePhase.Add(this.PhaseElapsed);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.PhaseElapsed]));
		w40.X = 340;
		w40.Y = 435;
		// Container child LayoutPagePhase.Gtk.Fixed+FixedChild
		this.LabelPhaseElapsed = new global::Gtk.Label();
		this.LabelPhaseElapsed.Name = "LabelPhaseElapsed";
		this.LabelPhaseElapsed.LabelProp = global::Mono.Unix.Catalog.GetString("Elapsed time (ms)");
		this.LayoutPagePhase.Add(this.LabelPhaseElapsed);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePhase[this.LabelPhaseElapsed]));
		w41.X = 490;
		w41.Y = 440;
		this.MainNotebook.Add(this.LayoutPagePhase);
		global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPagePhase]));
		w42.Position = 1;
		// Notebook tab
		this.LabelPagePhase = new global::Gtk.Label();
		this.LabelPagePhase.Name = "LabelPagePhase";
		this.LabelPagePhase.LabelProp = global::Mono.Unix.Catalog.GetString("Phase");
		this.MainNotebook.SetTabLabel(this.LayoutPagePhase, this.LabelPagePhase);
		this.LabelPagePhase.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPageReconstruction = new global::Gtk.Fixed();
		this.LayoutPageReconstruction.Name = "LayoutPageReconstruction";
		this.LayoutPageReconstruction.HasWindow = false;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.ReconImage = new global::Gtk.Image();
		this.ReconImage.WidthRequest = 256;
		this.ReconImage.HeightRequest = 256;
		this.ReconImage.Name = "ReconImage";
		this.LayoutPageReconstruction.Add(this.ReconImage);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.ReconImage]));
		w43.X = 70;
		w43.Y = 20;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.ReconScrollY = new global::Gtk.VScrollbar(null);
		this.ReconScrollY.HeightRequest = 256;
		this.ReconScrollY.Name = "ReconScrollY";
		this.ReconScrollY.Adjustment.Upper = 100D;
		this.ReconScrollY.Adjustment.PageIncrement = 10D;
		this.ReconScrollY.Adjustment.PageSize = 10D;
		this.ReconScrollY.Adjustment.StepIncrement = 1D;
		this.LayoutPageReconstruction.Add(this.ReconScrollY);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.ReconScrollY]));
		w44.X = 20;
		w44.Y = 20;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.ReconScrollX = new global::Gtk.HScrollbar(null);
		this.ReconScrollX.WidthRequest = 256;
		this.ReconScrollX.Name = "ReconScrollX";
		this.ReconScrollX.Adjustment.Upper = 100D;
		this.ReconScrollX.Adjustment.PageIncrement = 10D;
		this.ReconScrollX.Adjustment.PageSize = 10D;
		this.ReconScrollX.Adjustment.StepIncrement = 1D;
		this.LayoutPageReconstruction.Add(this.ReconScrollX);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.ReconScrollX]));
		w45.X = 70;
		w45.Y = 306;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.LabelPropagation = new global::Gtk.Label();
		this.LabelPropagation.Name = "LabelPropagation";
		this.LabelPropagation.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Propagation</b>");
		this.LabelPropagation.UseMarkup = true;
		this.LayoutPageReconstruction.Add(this.LabelPropagation);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.LabelPropagation]));
		w46.X = 340;
		w46.Y = 20;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.PropagationZ = new global::Gtk.SpinButton(-10000D, 10000D, 1D);
		this.PropagationZ.WidthRequest = 140;
		this.PropagationZ.Name = "PropagationZ";
		this.PropagationZ.Adjustment.PageIncrement = 1D;
		this.PropagationZ.ClimbRate = 1D;
		this.PropagationZ.Numeric = true;
		this.LayoutPageReconstruction.Add(this.PropagationZ);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.PropagationZ]));
		w47.X = 340;
		w47.Y = 130;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.PropagationScrollZ = new global::Gtk.HScrollbar(null);
		this.PropagationScrollZ.WidthRequest = 400;
		this.PropagationScrollZ.Name = "PropagationScrollZ";
		this.PropagationScrollZ.Adjustment.Lower = -10000D;
		this.PropagationScrollZ.Adjustment.Upper = 10000D;
		this.PropagationScrollZ.Adjustment.PageIncrement = 1D;
		this.PropagationScrollZ.Adjustment.PageSize = 1D;
		this.PropagationScrollZ.Adjustment.StepIncrement = 1D;
		this.LayoutPageReconstruction.Add(this.PropagationScrollZ);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.PropagationScrollZ]));
		w48.X = 340;
		w48.Y = 170;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.LabelPropagationZ1 = new global::Gtk.Label();
		this.LabelPropagationZ1.Name = "LabelPropagationZ1";
		this.LabelPropagationZ1.LabelProp = global::Mono.Unix.Catalog.GetString("Distance (&#956;m)");
		this.LabelPropagationZ1.UseMarkup = true;
		this.LayoutPageReconstruction.Add(this.LabelPropagationZ1);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.LabelPropagationZ1]));
		w49.X = 490;
		w49.Y = 135;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'ReconToolbar\'><toolitem name=\'ComputePropagationButton\' action" +
				"=\'ComputePropagationButton\'/><toolitem name=\'SaveReconstructionButton\' action=\'S" +
				"aveReconstructionButton\'/></toolbar></ui>");
		this.ReconToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/ReconToolbar")));
		this.ReconToolbar.Name = "ReconToolbar";
		this.ReconToolbar.ShowArrow = false;
		this.ReconToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.LayoutPageReconstruction.Add(this.ReconToolbar);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.ReconToolbar]));
		w50.X = 340;
		w50.Y = 200;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.PropagationWavelength = new global::Gtk.SpinButton(0D, 100000D, 1D);
		this.PropagationWavelength.WidthRequest = 140;
		this.PropagationWavelength.Name = "PropagationWavelength";
		this.PropagationWavelength.Adjustment.PageIncrement = 1D;
		this.PropagationWavelength.ClimbRate = 1D;
		this.PropagationWavelength.Numeric = true;
		this.LayoutPageReconstruction.Add(this.PropagationWavelength);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.PropagationWavelength]));
		w51.X = 340;
		w51.Y = 50;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.LabelPropagationWavelength = new global::Gtk.Label();
		this.LabelPropagationWavelength.Name = "LabelPropagationWavelength";
		this.LabelPropagationWavelength.LabelProp = global::Mono.Unix.Catalog.GetString("Wavelength (nm)");
		this.LayoutPageReconstruction.Add(this.LabelPropagationWavelength);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.LabelPropagationWavelength]));
		w52.X = 490;
		w52.Y = 55;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.PropagationPitch = new global::Gtk.SpinButton(0D, 10000D, 1D);
		this.PropagationPitch.WidthRequest = 140;
		this.PropagationPitch.Name = "PropagationPitch";
		this.PropagationPitch.Adjustment.PageIncrement = 1D;
		this.PropagationPitch.ClimbRate = 1D;
		this.PropagationPitch.Numeric = true;
		this.LayoutPageReconstruction.Add(this.PropagationPitch);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.PropagationPitch]));
		w53.X = 340;
		w53.Y = 90;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.LabelPropagationPitch = new global::Gtk.Label();
		this.LabelPropagationPitch.Name = "LabelPropagationPitch";
		this.LabelPropagationPitch.LabelProp = global::Mono.Unix.Catalog.GetString("Pitch (&#956;m)");
		this.LabelPropagationPitch.UseMarkup = true;
		this.LayoutPageReconstruction.Add(this.LabelPropagationPitch);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.LabelPropagationPitch]));
		w54.X = 490;
		w54.Y = 95;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.ReconElapsed = new global::Gtk.Entry();
		this.ReconElapsed.WidthRequest = 140;
		this.ReconElapsed.Name = "ReconElapsed";
		this.ReconElapsed.IsEditable = false;
		this.ReconElapsed.InvisibleChar = '•';
		this.LayoutPageReconstruction.Add(this.ReconElapsed);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.ReconElapsed]));
		w55.X = 340;
		w55.Y = 250;
		// Container child LayoutPageReconstruction.Gtk.Fixed+FixedChild
		this.LabelReconElapsed = new global::Gtk.Label();
		this.LabelReconElapsed.Name = "LabelReconElapsed";
		this.LabelReconElapsed.LabelProp = global::Mono.Unix.Catalog.GetString("Elapsed time (ms)");
		this.LayoutPageReconstruction.Add(this.LabelReconElapsed);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPageReconstruction[this.LabelReconElapsed]));
		w56.X = 490;
		w56.Y = 255;
		this.MainNotebook.Add(this.LayoutPageReconstruction);
		global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPageReconstruction]));
		w57.Position = 2;
		// Notebook tab
		this.LabelPageReconstruction = new global::Gtk.Label();
		this.LabelPageReconstruction.Name = "LabelPageReconstruction";
		this.LabelPageReconstruction.LabelProp = global::Mono.Unix.Catalog.GetString("Reconstruction");
		this.MainNotebook.SetTabLabel(this.LayoutPageReconstruction, this.LabelPageReconstruction);
		this.LabelPageReconstruction.ShowAll();
		this.MainLayout.Add(this.MainNotebook);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainNotebook]));
		w58.X = 20;
		w58.Y = 70;
		this.Add(this.MainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.QuitButton.Activated += new global::System.EventHandler(this.OnQuitButtonClicked);
		this.OpenInputButton.Activated += new global::System.EventHandler(this.OnOpenInputButtonClicked);
		this.SaveInputButton.Activated += new global::System.EventHandler(this.OnSaveInputButtonClicked);
		this.OpenPhaseButton.Activated += new global::System.EventHandler(this.OnOpenPhaseButtonClicked);
		this.SavePhaseButton.Activated += new global::System.EventHandler(this.OnSavePhaseButtonClicked);
		this.ComputePhaseButton.Activated += new global::System.EventHandler(this.OnComputePhaseButtonClicked);
		this.RemovePointButton.Activated += new global::System.EventHandler(this.OnRemovePointButtonClicked);
		this.DeletePointsButton.Activated += new global::System.EventHandler(this.OnDeletePointsButtonClicked);
		this.ComputeMultipointsPhase.Activated += new global::System.EventHandler(this.OnComputePhaseButtonClicked);
		this.ComputePropagationButton.Activated += new global::System.EventHandler(this.OnComputePropagationButtonClicked);
		this.SaveReconstructionButton.Activated += new global::System.EventHandler(this.OnSaveReconstructionButtonClicked);
		this.InputScrollY.ValueChanged += new global::System.EventHandler(this.OnInputScrollYValueChanged);
		this.InputEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnInputEventBoxButtonPressEvent);
		this.InputScrollX.ValueChanged += new global::System.EventHandler(this.OnInputScrollXValueChanged);
		this.NFFT.ValueChanged += new global::System.EventHandler(this.OnNFFTValueChanged);
		this.PhaseScrollY.ValueChanged += new global::System.EventHandler(this.OnPhaseScrollYValueChanged);
		this.PhaseScrollX.ValueChanged += new global::System.EventHandler(this.OnPhaseScrollXValueChanged);
		this.LensPhase.Toggled += new global::System.EventHandler(this.OnLensPhaseToggled);
		this.LensZ.ValueChanged += new global::System.EventHandler(this.OnLensZValueChanged);
		this.LensZScroll.ValueChanged += new global::System.EventHandler(this.OnLensZScrollValueChanged);
		this.Pitch.ValueChanged += new global::System.EventHandler(this.OnPitchValueChanged);
		this.Wavelength.ValueChanged += new global::System.EventHandler(this.OnWavelengthValueChanged);
		this.BlazedPhase.Toggled += new global::System.EventHandler(this.OnBlazedPhaseToggled);
		this.BlazedX.ValueChanged += new global::System.EventHandler(this.OnBlazedXValueChanged);
		this.BlazedScrollX.ValueChanged += new global::System.EventHandler(this.OnBlazedScrollXValueChanged);
		this.BlazedY.ValueChanged += new global::System.EventHandler(this.OnBlazedYValueChanged);
		this.BlazedScrollY.ValueChanged += new global::System.EventHandler(this.OnBlazedScrollYValueChanged);
		this.GerchbergSaxtonPhase.Toggled += new global::System.EventHandler(this.OnGerchbergSaxtonPhaseToggled);
		this.ReconScrollY.ValueChanged += new global::System.EventHandler(this.OnReconScrollYValueChanged);
		this.ReconScrollX.ValueChanged += new global::System.EventHandler(this.OnReconScrollXValueChanged);
		this.PropagationZ.ValueChanged += new global::System.EventHandler(this.OnPropagationZValueChanged);
		this.PropagationScrollZ.ValueChanged += new global::System.EventHandler(this.OnPropagationScrollZValueChanged);
		this.PropagationWavelength.ValueChanged += new global::System.EventHandler(this.OnPropagationWavelengthValueChanged);
		this.PropagationPitch.ValueChanged += new global::System.EventHandler(this.OnPropagationPitchValueChanged);
	}
}
